import { shape } from "../shape/shape"

export default shape({
    greek: {
        α: ["{alpha}", "alpha"],
        β: ["{beta}", "beta"],
        γ: ["{gamma}", "gamma"],
        δ: ["{delta}", "delta"],
        ε: ["{epsilon}", "epsilon"],
        ζ: ["{zeta}", "zeta"],
        η: ["{eta}", "eta"],
        θ: ["{theta}", "theta"],
        ι: ["{iota}", "iota"],
        κ: ["{kappa}", "kappa"],
        λ: ["{lambda}", "lambda"],
        μ: ["{mu}", "mu"],
        ν: ["{nu}", "nu"],
        ξ: ["{xi}", "xi"],
        ο: ["{omicron}", "omicron"],
        π: ["{pi}", "pi"],
        ρ: ["{rho}", "rho"],
        σ: ["{sigma}", "sigma"],
        τ: ["{tau}", "tau"],
        υ: ["{upsilon}", "upsilon"],
        φ: ["{phi}", "phi"],
        χ: ["{chi}", "chi"],
        ψ: ["{psi}", "psi"],
        ω: ["{omega}", "omega"],

        Α: ["{Alpha}", "Alpha"],
        Β: ["{Beta}", "Beta"],
        Γ: ["{Gamma}", "Gamma"],
        Δ: ["{Delta}", "Delta"],
        Ε: ["{Epsilon}", "Epsilon"],
        Ζ: ["{Zeta}", "Zeta"],
        Η: ["{Eta}", "Eta"],
        Θ: ["{Theta}", "Theta"],
        Ι: ["{Iota}", "Iota"],
        Κ: ["{Kappa}", "Kappa"],
        Λ: ["{Lambda}", "Lambda"],
        Μ: ["{Mu}", "Mu"],
        Ν: ["{Nu}", "Nu"],
        Ξ: ["{Xi}", "Xi"],
        Ο: ["{Omicron}", "Omicron"],
        Π: ["{Pi}", "Pi"],
        Ρ: ["{Rho}", "Rho"],
        Σ: ["{Sigma}", "Sigma"],
        Τ: ["{Tau}", "Tau"],
        Υ: ["{Upsilon}", "Upsilon"],
        Φ: ["{Phi}", "Phi"],
        Χ: ["{Chi}", "Chi"],
        Ψ: ["{Psi}", "Psi"],
        Ω: ["{Omega}", "Omega"]
    }
})
