import { shape } from "../../shape/shape"

export default shape({
    "∖": ["{s-}", "set:minus"],
    "∩": ["{s&}", "cap", "intersection", "inter"],
    "∪": ["{s|}", "union", "cup"],
    "⋂": ["{s&&}", "cap:big", "intersection:big", "inter:big"],
    "⋃": ["{s||}", "union:big", "cup:big"],
    "∧": ["{l&}", "and", "land"],
    "⋀": ["{l&&}", "and:big", "land:big"],
    "∨": ["{l|}", "or", "lor"],
    "⋁": ["{l||}", "or:big", "lor:big"],
    "¬": ["{l!}", "not", "lnot"],
    "∀": ["{A:}", "forall"],
    "∃": ["{E:}", "exists"],
    "∄": ["{!E:}", "exists:not", "nexists"],
    "∈": ["{e:}", "in"],
    "∉": ["{!e:}", "in:not", "nin"],
    "⊂": ["{s<:}", "subset", "sub"],
    "⊃": ["{s>:}", "superset", "sup"],
    "⊆": ["{s<=:}", "subset:equal", "subeq"],
    "⊇": ["{s>=:}", "superset:equal", "supeq"],
    "⊄": ["{!s<:}", "subset:not", "sub:not"],
    "⊅": ["{!s>:}", "superset:not", "sup:not"],
    "⊈": ["{!s<=:}", "subset:equal:not", "subeq:not"],
    "⊉": ["{!s>=:}", "superset:equal:not", "supeq:not"],
    "⊊": [null, "subset:proper", "psub"],
    "⊋": [null, "superset:proper", "psup"],
    "∅": ["{0}", "empty", "emptyset", "nullset"],
    "∴": ["{:.}", "therefore"],
    "∵": ["{.:}", "because"],
    "⟙": ["{T}", "top", "true", "tack:down"],
    "⟘": ["{F}", "bottom", "bot", "false", "tack:up"],
    "⊨": ["{|=}", "models", "vDash"],
    "⊭": ["{!|=}", "models:not", "vDash:not"],
    "⊩": ["{||-}", "forcecs", "Vdash"],
    "⊯": ["{!||-}", "forces:not", "Vdash:not"],
    "⊢": ["{|-}", "proves", "turnstile", "ts", "vdash", "tack:right"],
    "⊬": [
        "{!|-}",
        "proves:not",
        "turnstile:not",
        "ts:not",
        "vdash:not",
        "tack:right:not"
    ],
    "⊣": ["{-|}", "proven", "turnstile:rev", "dashv", "tack:left"]
})
